<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <RootNamespace>SimpleJson</RootNamespace>
    <AssemblyName>SimpleJson</AssemblyName>
  </PropertyGroup>

</Project>
